export * from './configsInterfaces/urls.interface';
export * from './propsComponents/providerRegionComponent.inteface';
export * from './sliceIntefaces/initialStateAndCervicesProvidersRegions.interface';
export * from './sliceIntefaces/movie.interface';
export * from './sliceIntefaces/initialStateArrowTop.interface';
export * from './actionsIntefaces/providerRegionSliceActionsetProvidersRegions.interface';
export * from './actionsIntefaces/error.inteface';
export * from './actionsIntefaces/getAllMovies.interface';
export * from './sliceIntefaces/genre.interface';
export * from './servicesIntefaces/genres.interface';
export * from './actionsIntefaces/genresAction.interface';
export * from './propsComponents/genreComponent.interface';
export * from './IUseLocation';
export * from './actionsIntefaces/movieWitchGenre.interface';
export * from './propsComponents/propsSelect.interface';
export * from './actionsIntefaces/pagePagination.interface';
export * from './actionsIntefaces/IMovieDetailAction.interface';
export * from './actionsIntefaces/getMoviesWithGenrePagination.interface';

