export enum QueryParamsEnum {
    comma = '&',
    language = 'language=',
    region = 'region=',
    sort_by = 'sort_by=',
    certification_country = 'certification_country=',
    certification = 'certification=',
    certificationLte = 'certification.lte=',
    certificationGte = 'certification.gte=',
    include_adult = 'include_adult=',
    include_video = "include_video=",
    page = 'page=',
    primary_release_year = 'primary_release_year=',
    primary_release_dateGte = 'primary_release_date.gte=',
    primary_release_dateLte = 'primary_release_date.lte=',
    release_dateGte = 'release_date.gte=',
    release_dateLte = 'release_date.lte=',
    with_release_type = 'with_release_type=',
    year = 'year=',
    with_genres = 'with_genres='
}